#ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM sonatype/nexus3:3.33.1


#RUN ls -l
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
COPY --chown=1000:1000 wait-for-it.sh wait-for-it.sh
COPY --chown=1000:1000 wait-for-it.sh /wait-for-it.sh

RUN whoami

RUN ls / -la
#RUN ls /virtual_elastic -la
#


#RUN chmod +x wait-for-it.sh
#RUN chmod +x /wait-for-it.sh


#USER elasticsearch

#
#RUN pwd
#RUN ls -l
