FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-slim

COPY . .
#ARG NEXUS_USERNAME
#ARG NEXUS_PASSWORD
#RUN ./mvnw --settings settings.xml package
RUN ls
RUN chmod +x ./mvnw

COPY wait-for-it.sh wait-for-it.sh
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x wait-for-it.sh
RUN chmod +x /wait-for-it.sh
