FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-slim
WORKDIR workdir

COPY . .
#ARG NEXUS_USERNAME
#ARG NEXUS_PASSWORD
#RUN ./mvnw --settings settings.xml package
RUN ls
RUN chmod +x ./mvnw

RUN chmod +x ./wait-for-it.sh
